<?xml version="1.0" encoding="UTF-8"?>
<!--
 sitemap.xsl: human readable view of RankKernel sitemaps.
 The sm: prefix must match the default namespace of the generated XML,
 otherwise every XPath matches nothing and browsers show an empty table.
-->
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="sm image">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 2rem; color: #1a1a1a; }
          h1 { font-size: 1.5rem; }
          table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
          th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          th { background: #f6f6f6; }
          a { color: #0066cc; text-decoration: none; }
          .desc { color: #555; margin-bottom: 1rem; }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <p class="desc">This XML Sitemap is generated by RankKernel for search engines.</p>
        <xsl:choose>
          <xsl:when test="sm:sitemapindex/sm:sitemap">
            <table>
              <thead><tr><th>Location</th><th>Last Modified</th></tr></thead>
              <tbody>
                <xsl:for-each select="sm:sitemapindex/sm:sitemap">
                  <tr>
                    <td><a><xsl:attribute name="href"><xsl:value-of select="sm:loc"/></xsl:attribute><xsl:value-of select="sm:loc"/></a></td>
                    <td><xsl:value-of select="sm:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:when>
          <xsl:when test="sm:urlset/sm:url">
            <table>
              <thead><tr><th>URL</th><th>Last Modified</th><th>Image</th></tr></thead>
              <tbody>
                <xsl:for-each select="sm:urlset/sm:url">
                  <tr>
                    <td><a><xsl:attribute name="href"><xsl:value-of select="sm:loc"/></xsl:attribute><xsl:value-of select="sm:loc"/></a></td>
                    <td><xsl:value-of select="sm:lastmod"/></td>
                    <td><xsl:value-of select="image:image/image:loc"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:when>
          <xsl:otherwise>
            <p>No entries found.</p>
          </xsl:otherwise>
        </xsl:choose>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
