<?xml version="1.0" encoding="UTF-8"?>
<!--
 sitemap.xsl: human readable view of RankKernel sitemaps.
 The sm: prefix must match the default namespace of the generated XML,
 otherwise every XPath matches nothing and browsers show an empty table.
 Layout follows the general sitemap index convention (heading, count line,
 entry table, back link) with original slate and emerald styling.
-->
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="sm image">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 2.5rem 1.5rem; color: #1f2937; background: #f9fafb; }
          .wrap { max-width: 1080px; margin: 0 auto; background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 2rem; }
          h1 { font-size: 1.5rem; margin: 0 0 0.5rem; }
          .desc { color: #4b5563; margin: 0 0 1rem; }
          .gen { color: #4b5563; margin: 0 0 0.5rem; font-size: 0.95rem; }
          .desc-block { width: 100%; padding-bottom: 0.5rem; margin-bottom: 1rem; border-bottom: 2px solid #0e7a5f; }
          .table-block { width: 100%; }
          .back { display: inline-block; margin-bottom: 1rem; color: #0e7a5f; text-decoration: none; font-weight: 600; }
          table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
          th, td { text-align: left; padding: 10px 14px; border-bottom: 1px solid #e5e7eb; word-break: break-word; }
          th { background: #1f2937; color: #fff; }
          a { color: #0e7a5f; text-decoration: none; }
          td.num { text-align: center; color: #4b5563; }
        </style>
      </head>
      <body>
        <div class="wrap">
          <xsl:choose>
            <xsl:when test="sm:sitemapindex/sm:sitemap">
              <div class="desc-block">
                <h1>XML Sitemap Index</h1>
                <p class="gen">This XML Sitemap Index is generated by RankKernel. It lists every sitemap on this site for search engines to crawl.</p>
              </div>
              <div class="table-block">
              <p class="desc">This XML Sitemap Index file contains <b><xsl:value-of select="count(sm:sitemapindex/sm:sitemap)"/></b> sitemaps.</p>
              <table>
                <thead><tr><th>Location</th><th>Last Modified</th></tr></thead>
                <tbody>
                  <xsl:for-each select="sm:sitemapindex/sm:sitemap">
                    <tr>
                      <td><a><xsl:attribute name="href"><xsl:value-of select="sm:loc"/></xsl:attribute><xsl:value-of select="sm:loc"/></a></td>
                      <td><xsl:value-of select="sm:lastmod"/></td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
              </div>
            </xsl:when>
            <xsl:when test="sm:urlset/sm:url">
              <div class="desc-block">
                <h1>XML Sitemap</h1>
                <p class="gen">This XML Sitemap is generated by RankKernel. It lists pages on this site for search engines to crawl.</p>
              </div>
              <div class="table-block">
              <a class="back" href="/sitemap_index.xml">&#8249; Sitemap Index</a>
              <p class="desc">This XML Sitemap contains <b><xsl:value-of select="count(sm:urlset/sm:url)"/></b> URLs.</p>
              <table>
                <thead><tr><th>URL</th><th>Last Modified</th><th>Images</th></tr></thead>
                <tbody>
                  <xsl:for-each select="sm:urlset/sm:url">
                    <tr>
                      <td><a><xsl:attribute name="href"><xsl:value-of select="sm:loc"/></xsl:attribute><xsl:value-of select="sm:loc"/></a></td>
                      <td><xsl:value-of select="sm:lastmod"/></td>
                      <td class="num"><xsl:value-of select="count(image:image)"/></td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
              </div>
            </xsl:when>
            <xsl:otherwise>
              <div class="desc-block">
                <h1>XML Sitemap</h1>
                <p class="gen">This XML Sitemap is generated by RankKernel.</p>
              </div>
              <div class="table-block">
              <a class="back" href="/sitemap_index.xml">&#8249; Sitemap Index</a>
              <p>No entries found.</p>
              </div>
            </xsl:otherwise>
          </xsl:choose>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
